# Generated by Django 2.2 on 2022-02-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Pople',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
