# Generated by Django 2.2 on 2022-02-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shop_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pople',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
