# Generated by Django 2.2 on 2022-02-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pople_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
