# Generated by Django 2.2 on 2022-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220226_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gp_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f1', models.CharField(max_length=200)),
                ('f2', models.CharField(max_length=200)),
                ('f3', models.CharField(max_length=200)),
                ('f4', models.CharField(max_length=200)),
                ('f5', models.CharField(max_length=200)),
                ('f6', models.CharField(max_length=200)),
                ('f7', models.CharField(max_length=200)),
                ('f8', models.CharField(max_length=200)),
                ('f9', models.CharField(max_length=200)),
                ('f10', models.CharField(max_length=200)),
                ('f11', models.CharField(max_length=200)),
                ('f12', models.CharField(max_length=200)),
                ('f13', models.CharField(max_length=200)),
                ('f14', models.CharField(max_length=200)),
                ('f15', models.CharField(max_length=200)),
                ('f16', models.CharField(max_length=200)),
                ('f17', models.CharField(max_length=200)),
                ('f18', models.CharField(max_length=200)),
                ('f19', models.CharField(max_length=200)),
                ('f20', models.CharField(max_length=200)),
                ('f21', models.CharField(max_length=200)),
                ('f22', models.CharField(max_length=200)),
                ('f23', models.CharField(max_length=200)),
                ('f24', models.CharField(max_length=200)),
                ('f25', models.CharField(max_length=200)),
                ('f26', models.CharField(max_length=200)),
                ('f27', models.CharField(max_length=200)),
                ('f28', models.CharField(max_length=200)),
                ('f29', models.CharField(max_length=200)),
            ],
        ),
    ]
