# Generated by Django 2.2.5 on 2022-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gp_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp_list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
