# Generated by Django 2.2 on 2022-05-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gp_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gp_list',
            new_name='Gpxx',
        ),
    ]
