# Generated by Django 2.2.5 on 2022-05-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220510_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
