# Generated by Django 2.2.5 on 2022-05-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220510_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gp_list',
        ),
    ]
