# Generated by Django 2.2.5 on 2022-05-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220510_2351'),
        ('app', '0015_gp_list'),
    ]

    operations = [
    ]
