# Generated by Django 2.2.5 on 2022-05-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220511_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='gp_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dm', models.CharField(max_length=200)),
                ('sj', models.CharField(max_length=200)),
                ('kp', models.CharField(max_length=200)),
                ('sp', models.CharField(max_length=200)),
                ('zg', models.CharField(max_length=200)),
                ('zd', models.CharField(max_length=200)),
                ('cjl', models.CharField(max_length=200)),
                ('cle', models.CharField(max_length=200)),
                ('zf', models.CharField(max_length=200)),
                ('zdf', models.CharField(max_length=200)),
                ('zdje', models.CharField(max_length=200)),
                ('hs', models.CharField(max_length=200)),
            ],
        ),
    ]
