# Generated by Django 2.2.5 on 2022-05-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_gp_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gp_list',
        ),
    ]
